#!/bin/zsh

export DOTFILES="$HOME/.dotfiles"

git clone "https://github.com/rin4046/dotfiles" "$DOTFILES"

ln -snfv "$DOTFILES/.zshrc" "$HOME/.zshrc"
ln -snfv "$DOTFILES/.vimrc" "$HOME/.vimrc"

mkdir -p "$HOME/.config"
ln -snfv "$DOTFILES/.config/"* "$HOME/.config"
