#!/bin/zsh

curl -o "$HOME/.zshrc" -L "https://raw.githubusercontent.com/rin4046/dotfiles/master/.zshrc"
curl -o "$HOME/.vimrc" -L "https://raw.githubusercontent.com/rin4046/dotfiles/master/.vimrc"
curl -o "$HOME/.local/zinit.zsh" -L "https://raw.githubusercontent.com/rin4046/dotfiles/master/zinit.zsh"
curl -o "$HOME/.config/kitty/kitty.conf" --create-dirs -L "https://raw.githubusercontent.com/rin4046/dotfiles/master/.config/kitty/kitty.conf"
