#!/bin/zsh

DOTFILES="$HOME/.dotfiles"

: "Install Homebrew" && {
  printf "\n\033[32m%s\033[m\n" "> Install Homebrew"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

: "git clone dotfiles" && {
  printf "\n\033[32m%s\033[m\n" "> github.com/rinrinrin4046/dotfiles -> ~/.dotfiles"
  git clone "https://github.com/rin4046/dotfiles" "$DOTFILES"
}

source "$DOTFILES/.zshenv"

: "Run some scripts" && {
  source "$DOTFILES/scripts/symlink.zsh"
  source "$DOTFILES/scripts/bundle.zsh"
  source "$DOTFILES/scripts/misc.zsh"
}

printf "\n\033[32m%s\033[m\n" "Done!"
